site_name: HEUOpenResource
site_description: HEUOpenResource
site_author: only9464
site_url: https://heuopenresource.github.io/heu-icicles/
dev_addr: '127.0.0.1:4000' #默认值
copyright: Copyright @ 2024 only9464, All rights reserved.
repo_url: https://github.com/HEUOpenResource/heu-icicles

theme:
  name: material
  language: zh # 一些提示性的文字会变成中文
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
 
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features: 
    - navigation.top   # 返回顶部的按钮 在上滑时出现
    - search.suggest   # 搜索输入一些字母时推荐补全整个单词
    - search.highlight   # 搜索出的文章关键词加入高亮
    - navigation.indexes   #启用节索引页后，可以将文档直接附加到节
    - search.share   #搜索分享按钮

extra:
  generator: false  #删除页脚显示“使用 MkDocs 材料制造”
  analytics: 
    provider: google
    property: G-SMFXWPCRMG # Google Analytics ID
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/HEUOpenResource/heu-icicles
    - icon: fontawesome/solid/envelope
      link: mailto:sky9464@qq.com
    - icon: fontawesome/solid/paper-plane
      link: https://t.me/+l17qIX7cFRNmNjg1 

extra_javascript:
  - '//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js'

nav:
  - 首页: index.md
